---
  
  - block:
    - name: Create latest ModPack directory
      ansible.builtin.file:
        path: "{{ minecraft_tmp }}/modpack"
        state: directory

    - name: Download latest ModPack
      ansible.builtin.get_url:
        url: "{{ curseforge_project_files.json.data[0].downloadUrl | regex_replace(' ', '%20') }}"
        dest: "{{ minecraft_tmp }}"
        checksum: "md5:{{ curseforge_project_files.json.data[0].hashes[1].value }}"

    - name: Extract latest ModPack
      ansible.builtin.unarchive:
        src: "{{ minecraft_tmp }}/{{ curseforge_project_files.json.data[0].fileName | regex_replace(' ', '+') }}"
        dest: "{{ minecraft_tmp }}/modpack"

    - name: Copy necessary ModPack directories with synchronize
      ansible.posix.synchronize:
        src: "{{ minecraft_tmp }}/modpack/{{ item }}"
        dest: "{{ minecraft_server }}"
      loop:
        - "overrides/config"
        - "overrides/defaultconfigs"
        - "overrides/patchouli_books"
        - "overrides/scripts"
    when: false
  


  - name: Define minecraft_version
    ansible.builtin.set_fact:
      minecraft_version: "{{ manifest.minecraft.version }}"
    when: minecraft_version is not defined

  - name: Define forge_version
    ansible.builtin.set_fact:
      forge_version: "{{ manifest.minecraft.modLoaders.id }}"
    when: forge_version is not defined