---

- name: Test jinja template

  become: yes
  become_method: sudo
  become_user: root

  hosts: localhost

  vars:
    sites: "{{ lookup('file', '/home/stephen/test.txt').splitlines()}}"

  tasks:

    - debug:
        msg: "{{ sites }}"

    - name: Create test.json from template
      ansible.builtin.template:
        src: templates/file.json.j2
        dest: "/home/stephen/test.json"