---

- name: Download Vault Hunters Server ModPack
  ansible.builtin.get_url:
    url: "{{ pack_url }}"
    dest: "{{ minecraft_tmp }}/{{ pack_name }}-{{ pack_version }}.zip"
    checksum: "{{ pack_checksum }}"

- name: Extract Vault Hunters Server ModPack
  ansible.builtin.unarchive:
    src: "{{ minecraft_tmp }}/{{ pack_name }}-{{ pack_version }}.zip"
    dest: "{{ minecraft_server }}"