---

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: yes

- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install required packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: latest