---

- include_vars: server.properties.yml
- include_vars: whitelist.json.yml
  
- name: Include minecraft config tasks
  include_tasks: minecraft_config.yml

- name: Include forge config tasks
  include_tasks: forge_config.yml

- name: Include server config tasks
  include_tasks: server_config.yml