---

- name: Download spark mod
  ansible.builtin.get_url:
    url: "https://media.forgecdn.net/files/3767/277/spark-1.9.1-forge.jar"
    dest: "{{ minecraft_server }}/mods"
    checksum: "md5:2d82da0ca51901f70360d555f1257bcd"

- name: Create server.properties from template
  ansible.builtin.template:
    src: templates/server.properties.j2
    dest: "{{ minecraft_server }}/server.properties"

- name: Create whitelist.json
  ansible.builtin.copy:
    content: "{{ whitelist | to_nice_json }}"
    dest: "{{ minecraft_server }}/whitelist.json"

- name: Create eula.txt
  ansible.builtin.copy:
    content: "eula=true"
    dest: "{{ minecraft_server }}/eula.txt"

- name: Create start.sh from template
  ansible.builtin.template:
    src: templates/start.sh.j2
    dest: "{{ minecraft_server }}/start.sh"
    mode: "a+x"