---

  - name: Get curseforge project info
    ansible.builtin.uri:
      url: "https://api.curseforge.com/v1/mods/{{ project_id }}/files"
      method: "GET"
      headers:
        Content-Type: "application/json"
        x-api-key: "{{ curseforge_api_key }}"
    register: curseforge_project_info

  - name: Get curseforge ServerPack file id
    ansible.builtin.set_fact:
      server_pack_id: "{{ curseforge_project_info.json | json_query(query) }}"
    vars:
      query: "data[?serverPackFileId].serverPackFileId | [0]"

  - name: Get curseforge ServerPack info
    ansible.builtin.uri:
      url: "https://api.curseforge.com/v1/mods/{{ project_id }}/files/{{ server_pack_id }}"
      method: "GET"
      headers:
        Content-Type: "application/json"
        x-api-key: "{{ curseforge_api_key }}"
    register: server_pack_info

  - name: Download latest ServerPack
    ansible.builtin.get_url:
      url: "{{ server_pack_info.json.data.downloadUrl | regex_replace(' ', '%20') }}"
      dest: "{{ minecraft_tmp }}/serverpack.zip"
      checksum: "md5:{{ server_pack_info.json.data.hashes[1].value }}"

  - debug:
      msg: "{{ minecraft_tmp }}/{{ server_pack_info.json.data.fileName | regex_replace(' ', '+') }}"

  - name: Extract latest ServerPack
    ansible.builtin.unarchive:
      src: "{{ minecraft_tmp }}/{{ server_pack_info.json.data.fileName | regex_replace(' ', '+') }}"
      dest: "{{ minecraft_server }}"

  - name: Create latest ModPack 1 directory
    ansible.builtin.file:
      path: "{{ minecraft_tmp }}/modpack"
      state: directory

  - name: Download latest ModPack 1
    ansible.builtin.get_url:
      url: "{{ curseforge_project_info.json.data[0].downloadUrl | regex_replace(' ', '%20') }}"
      dest: "{{ minecraft_tmp }}"
      checksum: "md5:{{ curseforge_project_info.json.data[0].hashes[1].value }}"

  - name: Extract latest ModPack 1
    ansible.builtin.unarchive:
      src: "{{ minecraft_tmp }}/{{ curseforge_project_info.json.data[0].fileName | regex_replace(' ', '%20') }}"
      dest: "{{ minecraft_tmp }}/modpack"

  - name: Copy necessary ModPack directories with synchronize
    ansible.posix.synchronize:
      src: "{{ minecraft_tmp }}/modpack/{{ item }}"
      dest: "{{ minecraft_server }}"
    loop:
      - "overrides/config"
      - "overrides/defaultconfigs"
      - "overrides/patchouli_books"
      - "overrides/scripts"