---

- name: Create minecraft group
  ansible.builtin.group:
    name: minecraft
    state: present

- name: Create minecraft user
  ansible.builtin.user:
    name: minecraft
    group: minecraft
    shell: /bin/bash
    system: yes
    state: present

- name: Create minecraft directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ minecraft_base }}"
    - "{{ minecraft_backups }}"
    - "{{ minecraft_server }}"
    - "{{ minecraft_scripts }}"
    - "{{ minecraft_tmp }}"


- name: retrieve version manifest
  ansible.builtin.uri:
    url: "{{ minecraft_version_manifest_url }}"
    return_content: true
  register: version_manifest

- name: get latest version
  set_fact:
    minecraft_version_latest: "{{ (version_manifest.content | from_json).latest.release }}"

- name: get latest version url
  set_fact:
    minecraft_version_latest_url: "{{ version_manifest.content | json_query(query) }}"
  vars:
    query: "versions[?id=='{{ minecraft_version_latest }}'].url"

- name: get latest version download url
  ansible.builtin.uri:
    url: "{{ minecraft_version_latest_url }}"
    return_content: true
  register: download_url

- name: get latest version download url
  set_fact:
    url: "{{ download_url.content | from_json).downloads.server.url }}"

- name: download latest version
  ansible.builtin.get_url:
    url: "{{ url }}"
    dest: "{{ minecraft_server }}"
    checksum: "sha1:{{ download_url.content | from_json).downloads.server.sha1 }}"
