---

- name: Include Minecraft variables
  include_vars: vars/main.yml

- name: Include setup tasks
- include_tasks: tasks/setup.yml

- name: Include download tasks
- include_tasks: tasks/download.yml