---

# Minecraft directories
minecraft_base: /opt/minecraft
minecraft_backups: /opt/minecraft/backups
minecraft_server: /opt/minecraft/server
minecraft_scripts: /opt/minecraft/scripts
minecraft_tmp: /opt/minecraft/tmp


minecraft_version_manifest_url: "https://launchermeta.mojang.com/mc/game/version_manifest.json"