---

- name: Create minecraft group
  ansible.builtin.group:
    name: minecraft
    state: present

- name: Create minecraft user
  ansible.builtin.user:
    name: minecraft
    group: minecraft
    shell: /bin/bash
    system: yes
    state: present

- name: Create minecraft directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: minecraft
    group: minecraft
    state: directory
  loop:
    - "{{ minecraft_base }}"
    - "{{ minecraft_backups }}"
    - "{{ minecraft_scripts }}"
    - "{{ minecraft_server }}"
    - "{{ minecraft_tmp }}"

- name: Allow ssh and minecraft port
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    state: enabled
  loop:
    - ssh
    - 25565