---

- name: Include any variables files
  ansible.builtin.include_vars:
    files:
      - server.properties.yml
      - whitelist.json.yml

- name: Include forge config tasks
  ansible.builtin.include_tasks: forge_config.yml

- name: Include curseforge config tasks
  ansible.builtin.include_tasks: curseforge_config.yml

- name: Include server config tasks
  ansible.builtin.include_tasks: server_config.yml